[package]
name = "ast_analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
syn = { version = "2.0", features = ["full", "visit"] }
toml = "0.8.12"
prettyplease = "0.2.19"
